# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\"\x1d\n\rLookupRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"O\n\x0eLookupResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"6\n\rUpdateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0fquantity_change\x18\x02 \x01(\x05\"H\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cnew_quantity\x18\x03 \x01(\x05\x32p\n\x0e\x43\x61talogService\x12.\n\x0bLookupStock\x12\x0e.LookupRequest\x1a\x0f.LookupResponse\x12.\n\x0bUpdateStock\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOKUPREQUEST']._serialized_start=17
  _globals['_LOOKUPREQUEST']._serialized_end=46
  _globals['_LOOKUPRESPONSE']._serialized_start=48
  _globals['_LOOKUPRESPONSE']._serialized_end=127
  _globals['_UPDATEREQUEST']._serialized_start=129
  _globals['_UPDATEREQUEST']._serialized_end=183
  _globals['_UPDATERESPONSE']._serialized_start=185
  _globals['_UPDATERESPONSE']._serialized_end=257
  _globals['_CATALOGSERVICE']._serialized_start=259
  _globals['_CATALOGSERVICE']._serialized_end=371
# @@protoc_insertion_point(module_scope)
