# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import order_pb2 as order__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/OrderService/PlaceOrder',
                request_serializer=order__pb2.OrderRequest.SerializeToString,
                response_deserializer=order__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.LookUpOrder = channel.unary_unary(
                '/OrderService/LookUpOrder',
                request_serializer=order__pb2.OrderLookUpRequest.SerializeToString,
                response_deserializer=order__pb2.OrderLookUpResponse.FromString,
                _registered_method=True)
        self.SyncOrder = channel.unary_unary(
                '/OrderService/SyncOrder',
                request_serializer=order__pb2.OrderSyncRequest.SerializeToString,
                response_deserializer=order__pb2.OrderSyncResponse.FromString,
                _registered_method=True)
        self.get_latest_transaction_id = channel.unary_unary(
                '/OrderService/get_latest_transaction_id',
                request_serializer=order__pb2.LastestOrderRequest.SerializeToString,
                response_deserializer=order__pb2.LatestOrderResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/OrderService/HealthCheck',
                request_serializer=order__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=order__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.LookUpOrdersById = channel.unary_unary(
                '/OrderService/LookUpOrdersById',
                request_serializer=order__pb2.LookUpByIdRequest.SerializeToString,
                response_deserializer=order__pb2.LookUpByIdResponse.FromString,
                _registered_method=True)
        self.BulkUpsert = channel.unary_unary(
                '/OrderService/BulkUpsert',
                request_serializer=order__pb2.BulkUpsertRequest.SerializeToString,
                response_deserializer=order__pb2.BulkUpsertResponse.FromString,
                _registered_method=True)


class OrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookUpOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_latest_transaction_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookUpOrdersById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkUpsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=order__pb2.OrderRequest.FromString,
                    response_serializer=order__pb2.OrderResponse.SerializeToString,
            ),
            'LookUpOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.LookUpOrder,
                    request_deserializer=order__pb2.OrderLookUpRequest.FromString,
                    response_serializer=order__pb2.OrderLookUpResponse.SerializeToString,
            ),
            'SyncOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncOrder,
                    request_deserializer=order__pb2.OrderSyncRequest.FromString,
                    response_serializer=order__pb2.OrderSyncResponse.SerializeToString,
            ),
            'get_latest_transaction_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_latest_transaction_id,
                    request_deserializer=order__pb2.LastestOrderRequest.FromString,
                    response_serializer=order__pb2.LatestOrderResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=order__pb2.HealthCheckRequest.FromString,
                    response_serializer=order__pb2.HealthCheckResponse.SerializeToString,
            ),
            'LookUpOrdersById': grpc.unary_unary_rpc_method_handler(
                    servicer.LookUpOrdersById,
                    request_deserializer=order__pb2.LookUpByIdRequest.FromString,
                    response_serializer=order__pb2.LookUpByIdResponse.SerializeToString,
            ),
            'BulkUpsert': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkUpsert,
                    request_deserializer=order__pb2.BulkUpsertRequest.FromString,
                    response_serializer=order__pb2.BulkUpsertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/PlaceOrder',
            order__pb2.OrderRequest.SerializeToString,
            order__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookUpOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/LookUpOrder',
            order__pb2.OrderLookUpRequest.SerializeToString,
            order__pb2.OrderLookUpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/SyncOrder',
            order__pb2.OrderSyncRequest.SerializeToString,
            order__pb2.OrderSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_latest_transaction_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/get_latest_transaction_id',
            order__pb2.LastestOrderRequest.SerializeToString,
            order__pb2.LatestOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/HealthCheck',
            order__pb2.HealthCheckRequest.SerializeToString,
            order__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookUpOrdersById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/LookUpOrdersById',
            order__pb2.LookUpByIdRequest.SerializeToString,
            order__pb2.LookUpByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkUpsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/BulkUpsert',
            order__pb2.BulkUpsertRequest.SerializeToString,
            order__pb2.BulkUpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
